version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-music-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/app
